title: Kasia Bryc
tagline: Population Genetecist
production_url: https://kasiabryc.com
#url: https://kasiabryc.com

author:
    name: Katarzyna Bryc
    email: kasia1@gmail.com
    github: kasia1

collections:
    content:
        # organizes static pages in a sub directory rather than root
        output: true
        permalink: /:path/index.html

defaults:
    -   scope: { path: "", type: pages }
        values: { layout: page }
    -   scope: { path: "", type: content }
        values: { layout: page }

JB:
    BASE_PATH: /
    #ASSET_PATH: false
    analytics:
        provider: googleUA
        googleUA:
            tracking_id: UA-51964066-2
            property_name: kasiabryc.com
    theme: journal

# Timezone for blog posts
timezone: America/Los_Angeles

# Files Jekyll should not copy to output tree
exclude:
    - CNAME
    - .gitignore
    - README.md
    - Gemfile

markdown: kramdown

kramdown:
    extensions: [autolink, footnotes, smart]
#    auto_ids: true

# GitHub Pages will enforce this anyway, precludes use of plugins
safe: true
lsi: false
